apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
spec:
  workspaces:
  - name: source
  params:
  - name: name
    type: string
    default: ""
  - name: revision
    type: string
    default: ""
  steps:
  - image: docker
    workingDir: $(workspaces.source.path)
    name: client
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2376
    - name: DOCKER_TLS_VERIFY
      value: '1'
    - name: DOCKER_CERT_PATH
      value: /certs/client
    script: |
        #!/usr/bin/env sh
        set -e

        docker login --username=mayconjrpacheco --password=23224c83-f9fd-4718-a99d-7b08ba951de9
        docker build -t mayconjrpacheco/pipes/$(params.name):$(params.revision) -f ./cmd/Dockerfile .
        docker push mayconjrpacheco/pipes/$(params.name):$(params.revision)
    volumeMounts:
    - mountPath: /certs/client
      name: dind-certs

  sidecars:
  - image: docker:dind
    name: server
    args:
      - --storage-driver=vfs
      - --userland-proxy=false
      - --debug
    resources:
      requests:
        memory: "512Mi"
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: /certs
    volumeMounts:
    - mountPath: /certs/client
      name: dind-certs
    readinessProbe:
      periodSeconds: 1
      exec:
        command: ['ls', '/certs/client/ca.pem']

  volumes:
  - name: dind-certs
    emptyDir: {}
